//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapateriaJossielito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesCompras
    {
        public int IdDetalleCompra { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Talla { get; set; }
        public string Color { get; set; }
        public int IdProducto_FK { get; set; }
        public int IdCompra_FK { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
